add switch tna-tea
ferminrp/compara-tasas pull request #16
Opened 2024-02-11 23:38 UTC by AdrielIg

- Enable swtiching between TNA and TEA.
- Add some types

Some files had to be converted to react so they can have dynamism

![Screenshot 2024-02-11 203523](https://github.com/ferminrp/compara-tasas/assets/75552918/4dce1731-1df6-4dae-878d-f5fd4e4c8f09)

2024-02-12 11:34 UTC, ferminrp requested changes
Sacaria el separador negro, el resto lo veo joya. De curioso nomas quiero entender por que volaste el meta keywords

2024-02-12 11:34 UTC, ferminrp commented on src/layouts/Layout.astro
al meta keywords por que lo hiciste cagar?

2024-02-12 11:34 UTC, ferminrp commented on src/components/Sections/InvestmentSection.tsx
> +      <div className='w-4/5 mx-auto border-b border-gray-700 my-8'></div>
El div que hace de linea separadora negra lo sacaria

2024-02-12 11:35 UTC, ferminrp commented
Por alguna razon, el toggle en experiencia tradicional se deforma en mobile
![image](https://github.com/ferminrp/compara-tasas/assets/21282919/f3685471-92a0-4870-92d1-165396e3e261)

2024-02-12 15:22 UTC, AdrielIg commented on src/layouts/Layout.astro
Cuak. Ni idea por qué no está por qué no toque nada del head jajaja. Ahora llego a casa y se lo vuelvo a poner

2024-02-12 15:23 UTC, AdrielIg commented on src/components/Sections/InvestmentSection.tsx
> +      <div className='w-4/5 mx-auto border-b border-gray-700 my-8'></div>
Dalex

2024-02-12 15:25 UTC, AdrielIg commented
> Por alguna razon, el toggle en experiencia tradicional se deforma en mobile
> 
> ![image](https://github.com/ferminrp/compara-tasas/assets/21282919/f3685471-92a0-4870-92d1-165396e3e261)
> 
> 

Me la juego que debe ser por que con "Experiencia Tradicional" se hace una doble línea para el texto entonces el height del switch crece y al tener position absolute se caga. Con darle un height al switch debería bastar. Hoy a la tarde lo fixeo

2024-02-14 21:49 UTC, ferminrp approved these changes

2024-02-14 21:53 UTC, merged